### ISSUE TITLE
Can't unpack dcx file

### ISSUE THREAD

**Issue by egbertwong** [JKAnderson/Yabber#4]
Decompressing DCX: 01_common.tpf.dcx...
Unhandled exception: System.FormatException: Unknown DCX format.
   在 SoulsFormats.DCX.Decompress(BinaryReaderEx br, Type& type)
   在 SoulsFormats.DCX.Decompress(String path, Type& type)
   在 Yabber.Program.UnpackFile(String sourceFile)
   在 Yabber.Program.Main(String[] args)

One or more errors were encountered and displayed above.

---------------------------------
It's a file from Sekiro.
These are the messages. How can I resolve it, please.
Thank you!

**Comment by JKAnderson** [comment]
Supported as of Yabber 1.3
