### ISSUE TITLE
Demon's Souls .tpf support

### ISSUE THREAD

**Issue by SonofUgly** [JKAnderson/Yabber#6]
It would be greatly appreciated if you could add support for this in Yabber, as currently there's no way to replace DeS' textures with higher resolution textures.
Here are some related scripts which may be helpful:
[Neosis .tpf unpacker](https://forum.xentax.com/viewtopic.php?p=98042&sid=50f34dffc9899d2e569e049dde6f959e#p98042)
[QuickBMS script for repacking .tpfs](https://zenhax.com/viewtopic.php?p=46539#p46539) only repacks textures of the same size.

**Comment by JKAnderson** [comment]
I don't anticipate doing console TPF repacking any time soon, if ever.
But, you can use [Horkbuild](https://github.com/horkrux/DeS-BNDBuild/releases) for that instead.

**Comment by SonofUgly** [comment]
Thank you, I hadn't seen horkrux's fork.
